name: LaTeX

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex
      - name: Rename the Result
        run: mv CV.pdf Resume-mhsaadatfar.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: Resume-mhsaadatfar.pdf

  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/download-artifact@master
      with:
        name: PDF
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@v1